apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: b-cartservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: b-cartservice
    spec:
      containers:
        - image: 159616352881.dkr.ecr.eu-west-1.amazonaws.com/microservices-demo-cartservice:latest
          name: b-cartservice
          imagePullPolicy: Always
          resources: {}
          ports:
            - name: b-cartservice
              containerPort: 7070
              protocol: TCP
          env:
            - name: POSTGRES_FOR_OTEL_CONNECTION_STRING
              value: "a246e90b79fd34b2e9105d5df8c526b9-1105414556.eu-west-1.elb.amazonaws.com:4317"
---
apiVersion: v1
kind: Service
metadata:
  name: b-cartservice
spec:
  ports:
    - name: b-cartservice
      port: 7070
      targetPort: 7070
      protocol: TCP
  selector:
    app.kubernetes.io/name: b-cartservice
  type: LoadBalancer