apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cartservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: cartservice
    spec:
      containers:
        - image: 159616352881.dkr.ecr.eu-west-1.amazonaws.com/microservices-demo-cartservice:latest
          name: cartservice
          imagePullPolicy: Always
          resources: {}
          ports:
            - name: cartservice
              containerPort: 7070
              protocol: TCP
          env:
            - name: POSTGRES_FOR_OTEL_CONNECTION_STRING
              value: "postgres://postgres:UUtryc100@temporal-postgre.dev.sealights.co:5432/traces"
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  ports:
    - name: cartservice
      port: 7070
      targetPort: 7070
      protocol: TCP
  selector:
    app.kubernetes.io/name: cartservice
  type: LoadBalancer